---
- name: update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: add {{ aws_cwa_package }} key
  apt_key:
    state: present
    url: "{{ aws_cwa_package_gpg }}"

- name: get the {{ aws_cwa_package }}.deb.sig remote file size
  uri:
    url: "{{ aws_cwa_package_signature }}"
    method: HEAD
    validate_certs: false
  register: url_pkg_sig

- name: get the {{ aws_cwa_package }}.deb remote file size
  uri:
    url: "{{ aws_cwa_package_url }}"
    method: HEAD
    validate_certs: false
  register: url_pkg

- name: check if {{ aws_cwa_package }}.deb.sig file exist before install
  stat:
    path: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.deb.sig"
  register: pkg_sig_file

- name: check if {{ aws_cwa_package }}.deb file exist before install
  stat:
    path: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.deb"
  register: pkg_file

- name: download {{ aws_cwa_package }}.deb.sig
  get_url:
    url: "{{ aws_cwa_package_url }}"
    dest: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.deb.sig"
  when: >
    not pkg_sig_file.stat.exists or
    url_pkg_sig.content_length != pkg_sig_file.stat.size
  changed_when: false

- name: download {{ aws_cwa_package }}.deb
  get_url:
    url: "{{ aws_cwa_package_url }}"
    dest: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.deb"
  when: >
    not pkg_file.stat.exists or
    url_pkg.content_length != pkg_file.stat.size
  changed_when: false

- name: verify {{ aws_cwa_package }} package signature
  shell: gpg --verify {{ aws_cwa_package }}.deb.sig {{ aws_cwa_package }}.deb
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr"
  changed_when: false
  args:
    executable: /bin/bash
    chdir: /{{ aws_cwa_temp_path }}

- name: install {{ aws_cwa_package }}.deb
  apt:
    deb: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.deb"
    state: present
  notify: restart amazon-cloudwatch-agent

- name: check if {{ aws_cwa_package }}.rpm.sig file exist after install
  stat:
    path: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.rpm.sig"
  register: pkg_sig_file

- name: check if {{ aws_cwa_package }}.rpm file exist after install
  stat:
    path: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.rpm"
  register: pkg_file

- name: remove downloaded {{ aws_cwa_package }}.deb.sig
  file:
    path: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.deb.sig"
    state: absent
  when: pkg_sig_file.stat.exists
  changed_when: false

- name: remove downloaded {{ aws_cwa_package }}.deb
  file:
    path: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.deb"
    state: absent
  when: pkg_file.stat.exists
  changed_when: false
